spring:
  datasource:
    # url: jdbc:postgresql://localhost:5432/ALPERE
    url: jdbc:postgresql://172.17.123.53:5432/ALPERE
    username: alpere
    password: alpere


liquibase:
  change-log: classpath:changelog/changelog-master.xml
  contexts: update
  enabled: true

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
